ALTER TABLE t_p95298898_file_manager_encrypt.documents
  ADD COLUMN IF NOT EXISTS fake_s3_key TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cdn_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fake_cdn_url TEXT DEFAULT NULL;
